# Select which runs to perform
enable_experiments: True
enable_simulations: True
enable_plotting: False
enable_comparison_study: False
enable_optimization_study: False
enable_run_statistics: False

# Select solver name; allowed: "gurobi" (license required), "highs", or "cbc"
#solver: "gurobi"
#solver: "cbc"
solver: "highs"

# Select metric for length estimation; allowed: "lp" or "jaccard"
#length_estimator: "lp"
length_estimator: "jaccard"

# Select parameter for fragmentation during data simulation
fragmentation_params:
  max_singletons: 15
  phantom_rate: 0.00
  noise_rate: 5e-6
  fragmentation_type: "c/y"
  noise_distribution: "uniform"  # 'normal' or 'uniform'
  5_prime_tag: 555.1294  # Standard START tag
  3_prime_tag: 455.1491  # Standard END tag