simulation:
  - seq: CUA104GU1A
    n_fragments:
      - 10
      - 20
      - 30
  - seq: CAGCAAAACGAUCAUAUAGAGAUCCGCAGU
    n_fragments:
      - 30
  
parameters:
  - max_n_parts: 2 # The maximum number of parts a fragment can be split into!

dev:
  envs:
    lionelmssq: /home/johannes/micromamba/envs/lionelmssq-dev