simulation: # Sequence convention is 5' to 3'
  # Random sequence generation with given length which is fragmented
  # "n_fragments" times, the mutation rate for base-pairs is also given
  random:
    seed: 42325345
    mutation_rate: 0.1
    strata:
      - num_seq: 50
        n_fragments:
#          - 30
          - 50

  # Hardcodes the sequences
  custom:
    - seq: CUA104GU0A
      n_fragments:
#        - 10
#        - 20
        - 50
      name: "testcase_01"
    - seq: GAUUGUCGUG #Shanice endlabelled test sequence
      n_fragments:
#        - 20
#        - 30
        - 50
#        - 100
#        - 200
      name: "testcase_02"
#    - seq: CAGCAAAACGAUCAUAUAGAGAUCCGCAGU
#      n_fragments:
##        - 30
#        - 50
##        - 200
##        - 400
#      name: "testcase_06"
#    - seq: CAGCAAAACGAUCAUAUAGA
#      n_fragments:
##        - 30
#        - 100
##        - 200
##        - 400
#      name: "testcase_07"

experiment:
  - seq: GAUUGUCGUG
    fragments: "0"
    meta: "meta.yaml"
    name: "testcase_03"
#  - seq: CAACAAGCGAGAGGUUCGAA
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_04"
#  - seq: AGAGGCUAAUAGUAAGUUAA
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_05"
#  - seq: GAU0CUAGAUC
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_01"
#  - seq: UUAGCCCG0GA
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_02"
#  - seq: UAAAUC9AGGU
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_03"
#  - seq: UCGA9AUUGAG
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_04"
#  - seq: GGUU0CUUCGGAUAUCGGCGG
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_05"
#  - seq: CCA0AGUGCUAA0UAAAUUGCC
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_06"
#  - seq: UGCCUCACCAC9AUCAUCCUG
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_mod_07"

# Longer sequences (>20mer)
#  - seq: AUAGAUAGCCUAAAUCUCAGAGCUA
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_25mer_01"
#  - seq: CAGCCCACCACGUGUAGUGGGCCUAGCAGU
#    fragments: "0"
#    meta: "meta.yaml"
#    name: "testcase_08"

# Select solver name; allowed: "gurobi" (license required) or "cbc"
#solver: "gurobi"
solver: "cbc"

# Select parameter for fragmentation during data simulation
fragmentation_params:
  ghost_rate: 0.00
  rel_error_rate: 0.000005
  breakage_line: "c/y"
  noise_distribution: "uniform" # 'normal' or 'uniform'
  mass_5_prime: 555.1294  # Standard START tag
  mass_3_prime: 455.1491  # Standard END tag