__use_yte__: true

datasets:
  simulation:
    path: ?input.simulation
    separator: "\t"

views:
  simulation:
    dataset: simulation
    render-table:
      columns:
        left:
          plot:
            ticks:
              scale: linear
        right:
          plot:
            ticks:
              scale: linear
        is_start:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
        is_end:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
        is_internal:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
        is_start_end:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
        single_nucleoside:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
        true_mass_with_backbone:
          plot:
            heatmap:
              scale: linear
        observed_mass:
          plot:
            heatmap:
              scale: linear
        is_ghost_fragment:
          spell:
            url: v1.1.3/logic/boolean
            with:
              true_value: "true"
              false_value: "false"
